### ISSUE TITLE
cmd pallete

### ISSUE THREAD

**Issue by goavn** [deomitrus/veonim#39]
execute ex commands from a friendlier gui. use the list cmds vimscript fns. 

in the future it would be nice to have external cmd_line + wild_menu. track neovim issues for progress. (could implement dirty hacks before neovim implements, but only if really bored [ and what's the benefit? ])

**Comment by deomitrus** [comment]
figure out how matchingcommands works in vimrc

**Comment by goavn** [comment]
```viml
function! Commands()
  silent! exe "norm! :\<c-a>\"\<home>let\ cmds=\"\<cr>"
  return split(cmds, '\s\+')
endfun
```
